### ISSUE TITLE
ERROR: UndefVarError: `NlpPipe` not defined

### ISSUE THREAD

**Issue by 702ph** [michellekappl/Preprocessing_Pipeline_JuML#11]
## Description
The following line in the example provided in the `README.md` throws an error when executed:
```
pipe = NlpPipe(corpus) |> remove_noise |> tokenize |> one_hot_encoding
```

Error message:
```
ERROR: UndefVarError: `NlpPipe` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

## Environment
- Julia 1.10.7+0.aarch64.apple.darwin14
- macOS 15.1（24B83）

## To Reproduce
Follow the steps in the `README.md`, executing the code examples sequentially from top to bottom.

## Proposed Solution
The line that loads the required package with `using`
https://github.com/michellekappl/Preprocessing_Pipeline_JuML/blob/ee5c2060d1fd9dbc3f8b4ac646e16fede16e1d64/README.md?plain=1#L59 

should be executed *before* the example line:
https://github.com/michellekappl/Preprocessing_Pipeline_JuML/blob/ee5c2060d1fd9dbc3f8b4ac646e16fede16e1d64/README.md?plain=1#L39

**Comment by leonschreiber96** [comment]
Proposed solution implemented, merry xmas :) 🎄
